services:
    theater-service:
        container_name: theater-service
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env.production.local
        networks:
            - kirt08

networks:
    kirt08:
        external: true